<?php
    $imgurl = IMAGESERVE_DIR . "/images/$type/$file.$type";
    $protocol = isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] != "off" ? "https" : "http";
    $stylesheetDir = IMAGESERVE_DIR . "/assets/css/style.css";
?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>File - <?php echo $file . '.' . $type; ?></title>
        <link rel="stylesheet" href="<?php echo $stylesheetDir; ?>">
<?php if (TWITTER_CARDS) { ?>
        <meta name="twitter:image" content="<?php echo $protocol; ?>://<?php echo $_SERVER['SERVER_NAME'] . $imgurl; ?>" />
        <meta property="og:type" content="video.other">
        <meta property="og:url" content="<?php echo $protocol; ?>://<?php echo $_SERVER['SERVER_NAME'] . htmlspecialchars($_SERVER['
        REQUEST_URI']); ?>">
        <meta property="og:site_name" content="Lerndmina.Dev - CDN">
        <meta property="og:title" content="View <?php echo $file . '.' . $type; ?>">
        <meta property="og:image" content="<?php echo $protocol; ?>://<?php echo $_SERVER['SERVER_NAME'] . $imgurl; ?>">
        <meta name="twitter:card" content="photo">
        <meta name="twitter:title" content="<?php echo 'Image - ' . $file . '.' . $type; ?>">
        <meta name="twitter:site" content="<?php echo TWITTER_HANDLE; ?>">
        <link rel="image_src" href="<?php echo $protocol; ?>://<?php echo $_SERVER['SERVER_NAME'] . htmlspecialchars($_SERVER['
        REQUEST_URI']); ?>">
        <meta name="theme-color" content="#FF8764">

        <!-- FONT -->
        <link rel="preconnect" href="https://fonts.gstatic.com">
		<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@500&display=swap" rel="stylesheet"> 

<?php } ?>
    </head>
    <body>
        <h1>
            <a href="https://lerndmina.dev"></a>

            <?php echo "$file.$type"; ?> -<!-- &middot; -->

            <abbr title="Value rounded to the nearest kb.">
                ~<?php echo round($filesize / 1048576, 1); ?>MB
            </abbr>

        </h1>
                <h2>
                	<a href="<?php echo $imgurl; ?>">
            			<?php echo 'Direct Link - ' . $file . '.' . $type; ?>
            		</a>
                </h2>
        <div class="container">
            <?php if ($type != "mp4"): ?> <!-- To change back to WebM, use "webm" instead of mp4 -->
            <img src="<?php echo $imgurl; ?>" alt="<?php echo "$file.$type"; ?>">
            <?php else: ?>
            <video width="1280" height="720" controls>
                <source src="<?php echo $imgurl; ?>" type="video/mp4"> <!-- To change back to WebM, use "video/webm" instead of mp4 -->
            </video>
            <?php endif; ?>
        </div>

        <?php
            $time = microtime();
            $time = explode(' ', $time);
            $time = $time[1] + $time[0];
            $finish = $time;
            $total_time = round(($finish - $start), 5);
        ?>

        <p>
             Page generated in <?php echo $total_time; ?> seconds 
        </p>
        <?php require_once('assets/php/footer.php') ?>
    </body>
</html>
